import { Company as CompanyType } from './types/company';

export const Company = (company: CompanyType): CompanyType => ({
  app: {
    url: company?.app?.url || '',
    name: company?.app?.name || '',
    branch: company?.app?.branch || '',
    domain: company?.app?.domain || '',
    theme: {
      bgColor: company.app.theme.bgColor,
      textColor: company.app.theme.textColor,
      primaryColor: company.app.theme.primaryColor,
      primaryTextColor: company.app.theme.primaryTextColor,
      secondaryColor: company.app.theme.secondaryColor,
      secondaryTextColor: company.app.theme.secondaryTextColor,
    },
    description: company?.app?.description || '',
    scheduleInterval: company?.app?.scheduleInterval || 0,
  },
  plan: {
    id: company.plan.id,
    name: company.plan.name,
    price: company.plan.price,
    billing: company?.plan?.billing || 0,
    dueDate: company?.plan?.dueDate || new Date(),
    history: company.plan.history,
  },
  image: {
    logo: company?.image?.logo || '',
    about: company?.image?.about || '',
    icon: company?.image?.icon || {
      default: company?.image?.icon?.default || '',
      '72x72': company?.image?.icon?.['72x72'] || '',
      '96x96': company?.image?.icon?.['96x96'] || '',
      '128x128': company?.image?.icon?.['128x128'] || '',
      '144x144': company?.image?.icon?.['144x144'] || '',
      '152x152': company?.image?.icon?.['152x152'] || '',
      '192x192': company?.image?.icon?.['192x192'] || '',
      '384x384': company?.image?.icon?.['384x384'] || '',
      '512x512': company?.image?.icon?.['512x512'] || '',
    },
    cover: company?.image?.cover || {
      app: company?.image?.cover?.app || '',
      desktop: company?.image?.cover?.desktop || '',
    },
  },
  owner: {
    userId: company.owner.userId,
    name: company.owner.name,
    cpf: company?.owner?.cpf || '',
    dateBirth: company?.owner?.dateBirth || '',
    motherName: company?.owner?.motherName || '',
    phones: company.owner.phones,
    address: company.owner.address,
  },
  address: {
    lat: company?.address?.lat || 0,
    lng: company?.address?.lng || 0,
    city: company?.address?.city || '',
    state: company?.address?.state || '',
    number: company?.address?.number || '',
    street: company?.address?.street || '',
    zipcode: company?.address?.zipcode || '',
    district: company?.address?.district || '',
    shortState: company?.address?.shortState || '',
    complement: company?.address?.complement || '',
  },
  timezone: {
    id: company.timezone.id,
    utc: company.timezone.utc,
    offset: company.timezone.offset,
  },
  pagseguro: {
    id: company?.pagseguro?.id || '',
    email: company.pagseguro.email,
    oldToken: company?.pagseguro?.oldToken || '',
    publicKey: company?.pagseguro?.publicKey || '',
    token: company?.pagseguro?.token,
    maxInstallment: company.pagseguro.maxInstallment,
    maxInstallmentNoInterest: company.pagseguro.maxInstallmentNoInterest,
  },
  name: company.name,
  email: company?.email || '',
  wizard: company.wizard,
  cpfCnpj: company?.cpfCnpj || '',
  branchIds: company.branchIds,
  terms: company.terms,
  socialReason: company?.socialReason || '',
  phones: company.phones,
  openingHours: company.openingHours,
  id: company.id,
  projectId: company.projectId,
  companyId: company.companyId,
  createdAt: company.createdAt || new Date(),
  updatedAt: company.updatedAt || undefined,
  deletedAt: company.deletedAt || undefined,
});
